channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.1.2
- pip:
  - mlflow==2.11.0
  - cloudpickle==2.2.1
  - numpy==1.25.0
  - packaging==23.0
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.11.1
name: mlflow-env
